name: Nightly Test

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ocp-tests:
    uses: ./.github/workflows/reusable-ocp-tests.yml
    secrets: inherit
