---
name: Test Changes

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Shfmt
        uses: mfinelli/setup-shfmt@a25fda4c1fe115aec0f85e04126610841bc3141d # v4.0.1

      - name: Lint shell scripts
        run: make lint

  ocp-tests:
    uses: ./.github/workflows/reusable-ocp-tests.yml
    with:
      skip-dependabot: true
    secrets: inherit
